# For more information about the configurations used
# in this file, please see the Travis CI documentation.
#
# https://docs.travis-ci.com

before_install:
  - |

      # Install `ShellCheck`
      if [ "$TRAVIS_OS_NAME" = "osx" ]; then
        brew install shellcheck
      fi

language: generic

matrix:
  include:

    - os: osx
      osx_image: xcode11

notifications:
  email:
    on_failure: always
    on_success: never

script:
  - ./tests/shellcheck.sh
